version: '3'

services:
  vernemq:
    image: erlio/docker-vernemq
    environment:
        - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=off
        - DOCKER_VERNEMQ_LOG__CONSOLE__LEVEL=debug
        - DOCKER_VERNEMQ_PLUGINS.vernemq_demo_plugin=on
        - DOCKER_VERNEMQ_PLUGINS.vernemq_demo_plugin.path=/path/to/plugin
        - DOCKER_VERNEMQ_PLUGINS.vmq_passwd=off
        - DOCKER_VERNEMQ_PLUGINS.vmq_acl=off
        - AWS_ACCESS_KEY_ID=
        - AWS_SECRET_ACCESS_KEY=
        - COGNITO_USER_POOL_ID=
        - COGNITO_CLIENT_ID=
    volumes:
        - ./vernemq_demo_plugin/_build/default:/path/to/plugin
    ports:
        - 8883:8883
        - 1883:1883
        - 8888:8888
