Http:
    Port: ":2101"

Https:
    Port: ":2102"
    CertificateFile: "/root/config/cert.pem"
    PrivateKeyFile: "/root/config/key.pem"

Cognito:
    UserPoolId: "ap-southeast-2_Vr0EvkjSQ"
    ClientId: "5ltsi83d284v80775qvv46l370"
